#!/bin/bash

cp git/.gitconfig ~/.gitconfig
cp vim/.vimrc  ~/.vimrc
cp bash/.bashrc ~/.bash_profile
cp input/.inputrc ~/.inputrc

# Sublime text files
# OS X
cp sublime/Preferences.sublime-settings  ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Preferences.sublime-settings
# Linux
# cp sublime/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User
# Linux
# cp sublime/Default\ \(Linux\).sublime-keymap ~/.config/sublime-text-3/Packages/User
